C1                              =  60.4;                   % UNITS               Constant
C2                              =  0.0;                    % UNITS               Constant
C3                              =  0.0;                    % UNITS               Constant
D1                              =  0.8;                    % UNITS               Constant
D2                              =  0.2;                    % UNITS               Constant
D3                              =  0.05;                   % UNITS               Constant
G                               =  9.81;                   % UNITS               Constant
IC11                            =  0.0603;                 % UNITS               Constant
IC22                            =  0.12;                   % UNITS               Constant
IC33                            =  0.0603;                 % UNITS               Constant
ID11                            =  1.84;                   % UNITS               Constant
ID12                            =  0.0;                    % UNITS               Constant
ID22                            =  2.2;                    % UNITS               Constant
ID23                            =  0.0;                    % UNITS               Constant
ID31                            =  0.48;                   % UNITS               Constant
ID33                            =  0.56;                   % UNITS               Constant
IF11                            =  0.0584;                 % UNITS               Constant
IF12                            =  0.0;                    % UNITS               Constant
IF22                            =  0.06;                   % UNITS               Constant
IF23                            =  0.0;                    % UNITS               Constant
IF31                            =  0.0091;                 % UNITS               Constant
IF33                            =  0.0076;                 % UNITS               Constant
IG11                            =  0.1405;                 % UNITS               Constant
IG22                            =  0.28;                   % UNITS               Constant
IG33                            =  0.1405;                 % UNITS               Constant
IH11                            =  3.68;                   % UNITS               Constant
IH12                            =  0.0;                    % UNITS               Constant
IH22                            =  4.4;                    % UNITS               Constant
IH23                            =  0.0;                    % UNITS               Constant
IH31                            =  0.96;                   % UNITS               Constant
IH33                            =  1.12;                   % UNITS               Constant
IJ11                            =  3.68;                   % UNITS               Constant
IJ12                            =  0.0;                    % UNITS               Constant
IJ22                            =  4.4;                    % UNITS               Constant
IJ23                            =  0.0;                    % UNITS               Constant
IJ31                            =  0.96;                   % UNITS               Constant
IJ33                            =  1.12;                   % UNITS               Constant
K1                              =  876;                    % UNITS               Constant
K2                              =  128;                    % UNITS               Constant
K3                              =  20;                     % UNITS               Constant
L1                              =  0.4;                    % UNITS               Constant
L2                              =  -0.275;                 % UNITS               Constant
L3                              =  0.45;                   % UNITS               Constant
L4                              =  0.1;                    % UNITS               Constant
L5                              =  -0.05;                  % UNITS               Constant
L6                              =  -.45;                   % UNITS               Constant
L7                              =  -0.225;                 % UNITS               Constant
L8                              =  -0.8;                   % UNITS               Constant
L9                              =  0.25;                   % UNITS               Constant
L10                             =  -0.2;                   % UNITS               Constant
L11                             =  0.0;                    % UNITS               Constant
L12                             =  -0.1;                   % UNITS               Constant
LAMBDA                          =  pi/10;                  % UNITS               Constant
MC                              =  2;                      % UNITS               Constant
MD                              =  15;                     % UNITS               Constant
MF                              =  4;                      % UNITS               Constant
MG                              =  3;                      % UNITS               Constant
MH                              =  30;                     % UNITS               Constant
MJ                              =  38;                     % UNITS               Constant
RF                              =  0.35;                   % UNITS               Constant
RR                              =  0.3;                    % UNITS               Constant

Q1                              =  0.0;                    % UNITS               Initial Value
Q2                              =  0.0;                    % UNITS               Initial Value
Q3                              =  0.0;                    % UNITS               Initial Value
Q4                              =  0.0;                    % UNITS               Initial Value
Q5                              =  0.0;                    % UNITS               Initial Value
Q7                              =  0.0;                    % UNITS               Initial Value
Q8                              =  0.0;                    % UNITS               Initial Value
Q9                              =  0.0;                    % UNITS               Initial Value
Q10                             =  0.0;                    % UNITS               Initial Value
Q11                             =  0.0;                    % UNITS               Initial Value
U4                              =  0.5;                    % UNITS               Initial Value
U5                              =  -4.6/RR;                % UNITS               Initial Value
U7                              =  0.0;                    % UNITS               Initial Value
U9                              =  0.0;                    % UNITS               Initial Value
U10                             =  0.0;                    % UNITS               Initial Value
U11                             =  0.0;                    % UNITS               Initial Value

TINITIAL                        =  0.0;                    % sec                 Initial Time
TFINAL                          =  5.0;                    % sec                 Final Time
INTEGSTP                        =  0.05;                   % sec                 Integration Step
PRINTINT                        =  1;                      % Positive Integer    Print-Integer
ABSERR                          =  1.0E-08;                %                     Absolute Error
RELERR                          =  1.0E-07 ;               %                     Relative Error